const HASHTAGS_REGULAR_EXPRESSION = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;
const COMMENT_MAX_LENGTH = 140;
const HASHTAGS_MAX_COUNT = 5;
const HASHTAGS_MAX_LENGTH = 20;
const PHOTO_DESCRIPTIONS_COUNT = 25;
const NUMBER_OF_COMMENTS = 7;

export { HASHTAGS_REGULAR_EXPRESSION,
  COMMENT_MAX_LENGTH,
  HASHTAGS_MAX_COUNT,
  HASHTAGS_MAX_LENGTH,
  PHOTO_DESCRIPTIONS_COUNT,
  NUMBER_OF_COMMENTS,
};
