const HASHTAG_REGULAR_EXPRESSION = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;
const COMMENT_MAX_LENGTH = 140;
const HASHTAG_MAX_COUNT = 5;
const HASHTAG_MAX_LENGTH = 20;
const COMMENTS_PORTION = 5;
const ALERT_TIME = 15000;
const RERENDER_DELAY = 500;

export { HASHTAG_REGULAR_EXPRESSION,
  COMMENT_MAX_LENGTH,
  HASHTAG_MAX_COUNT,
  HASHTAG_MAX_LENGTH,
  COMMENTS_PORTION,
  ALERT_TIME,
  RERENDER_DELAY
};
